[ 2025-03-09 01:46:15,380 ] 25 root - INFO: Database Connection Sucessful !!!
[ 2025-03-09 01:46:15,400 ] 22 root - INFO: -------------------------------------------Pipeline initialized successfully------------------------------------
[ 2025-03-09 01:46:17,503 ] 723 root - INFO: Initiating get asset details pipeline
[ 2025-03-09 01:46:17,503 ] 725 root - INFO: Checking if asset exists
[ 2025-03-09 01:46:17,503 ] 139 root - INFO: <<< Calling Asset Exists Component
[ 2025-03-09 01:46:17,504 ] 25 root - INFO: Database Connection Sucessful !!!
[ 2025-03-09 01:46:17,504 ] 13 root - INFO: MySql Database Connection Sucessfull for Asset Type Exists Component !!!
[ 2025-03-09 01:46:17,739 ] 733 root - INFO: Completed checking asset exists or not
[ 2025-03-09 01:46:17,742 ] 735 root - INFO: Initiating Get Asset Details Operation
[ 2025-03-09 01:46:17,742 ] 159 root - INFO: <<< Calling AssetOperations Component
[ 2025-03-09 01:46:17,742 ] 25 root - INFO: Database Connection Sucessful !!!
[ 2025-03-09 01:46:17,742 ] 13 root - INFO: AssetTypeOperations initialized successfully
[ 2025-03-09 01:46:17,970 ] 162 root - INFO: asset details - > (id=1, asset_type_id=1, asset_name=landline phone, location=Baner, brand=BSNL, purchase_year=2025, is_active=True, current_owner=5, 'Electronics')
[ 2025-03-09 01:46:17,971 ] 177 root - INFO: Failed to get asset details for asset id 1
[ 2025-03-09 01:46:17,972 ] 165 root - INFO: Error Calling AssetOperations Component (get asset details) Error occurred in script [asset_operations.py] at line [178]: Error occurred in script [resultproxy.pyx] at line [54]: Error getting asset details for asset Error occurred in script [resultproxy.pyx] at line [54]: tuple indices must be integers or slices, not str
[ 2025-03-09 01:46:17,972 ] 747 root - ERROR: Error in get asset details pipeline!!! - Error occurred in script [__init__.py] at line [166]: Error occurred in script [asset_operations.py] at line [178]: Error occurred in script [resultproxy.pyx] at line [54]: Error getting asset details for asset Error occurred in script [resultproxy.pyx] at line [54]: tuple indices must be integers or slices, not str
